Ajout des docstrings de build_reports.py
139bercy/propilot2pdf pull request #48
Opened 2021-08-05 10:17 UTC by QMaire

2021-08-05 10:17 UTC, QMaire commented
Seul le fichier build_report.py a été traité.
Les autres arriveront progressivement

2021-08-05 12:16 UTC, desrousseaux commented on build_reports.py
> +    """ Create a folder if is not exist"""
if it doesn't exist

2021-08-05 12:16 UTC, desrousseaux commented on build_reports.py
> +    """ Add unite after amount """
unit

2021-08-05 12:16 UTC, desrousseaux commented on build_reports.py
> +    """ Check if in pp_reg we have all regions and measures """
mettre in pp_reg à la fin de la phrase

2021-08-05 12:16 UTC, desrousseaux commented on build_reports.py
> +    """ Check if in pp_nat we have all measures"""
mettre in pp_nat à la fin de la phrase

2021-08-05 12:16 UTC, desrousseaux commented on build_reports.py
> +    """ For each date in last_dates_to_keep, if the date is missing in df_plot then we complete with na_replacement """
s/complete/fill

2021-08-05 12:16 UTC, desrousseaux commented on build_reports.py
> +    """ For one mesure and one maille, create every tables we need to generate parlementary file, and stock them in all_charts_as_df.
every table

2021-08-05 12:16 UTC, desrousseaux commented on build_reports.py
> +    Behind, layout of one created table with pp_dep:
Below

2021-08-05 12:16 UTC, desrousseaux commented on build_reports.py
> +            - Check if in all_charts_as_df, there are all tables for each department, regions and for the key France"""
Check if all charts_as_df contains ...

2021-08-05 12:16 UTC, desrousseaux commented on build_reports.py
> +    """ Business fonction. Only some measures will be present in parlementary file and for the latter
On peut enlever le Business function je pense

2021-08-05 12:16 UTC, desrousseaux commented on build_reports.py
> +    """ Create for one departement, the front page of the parlementary file """
Given a departement, creates the front ...

2021-08-05 12:16 UTC, desrousseaux commented on build_reports.py
> +    """ Create for one departement, the "volet" page of the parlementary file """
Given a departement, creates...

2021-08-05 12:16 UTC, desrousseaux commented on build_reports.py
> +    """ Create one page for parlementary file. This page is composed of 3 tables (departmental, regional, national) for one measure  """
This page is made of...

2021-08-05 13:25 UTC, QMaire commented
build_reports.py corrigé après Review
transpose_comments.py ajouté

2021-08-10 07:42 UTC, vesran requested changes

2021-08-10 07:42 UTC, vesran commented on build_reports.py
> +    Create crossing dictionnary between Mesure (key) and Indicateur (value)
" CreateS crossing ..."
The function creates a crossing dictionary.

2021-08-10 07:42 UTC, vesran commented on build_reports.py
> +def months_to_insert(modulo: int = 0, months: tuple = months, nb_mois: int = 3) -> list:
WOuld it be better to say 
```
def insert_months_to(...)
```
to keep the structure verb-complement ?

2021-08-10 07:42 UTC, vesran commented on build_reports.py
> +            ------------------------
Not sure whether mesure is a dataframe header or not.

2021-08-10 07:42 UTC, vesran commented on docx2pdf.py
> +    Create crossing dictionnary between department and department's number
Creates crossing dictionnary between department's **name** and department's number

2021-08-10 07:42 UTC, vesran commented on main_convert_parlementary_file_with_new_comment.py
> +    Create a zip in archive/Month_Year with 2 folders: folder_pdf and forlder_docx
Creates a zip in archive/Month_Year with 2 folders: folder_pdf and folder_docx

2021-08-10 07:42 UTC, vesran commented on main_create_parlementary_file.py
> +    Create a zip in archive/Month_Year with 2 folders: folder_pdf and forlder_docx
Creates a zip in archive/Month_Year with 2 folders: folder_pdf and folder_docx

2021-08-10 07:42 UTC, vesran commented on transpose_comments.py
> +    ???
Creates a generator that generates the smallest list for nested lists : [ [[.], [., .], [.]], [ [a], [.] ] ] --> [.], [., .], [.], [a], [.]

2021-08-10 07:42 UTC, vesran commented on transpose_comments.py
> +
... The image size is fixed since it cannot be extracted from the initial document.

2021-08-10 08:40 UTC, vesran approved these changes

2021-08-10 09:55 UTC, merged